// Travel phrases + health-card allergen translations per language.
// Machine-drafted first pass — flagged in-app as needing native review.
// Phrase ids/categories mirror the app's bundled pack schema exactly.
// P = [id, local, phonetic]; ids: bathroom howmuch help hello thanks excuse
// understand english doctor police water bill

const IDS = ["bathroom","howmuch","help","hello","thanks","excuse","understand","english","doctor","police","water","bill"];
const EN = {
  bathroom: "Where is the bathroom?", howmuch: "How much does it cost?", help: "Help!",
  hello: "Hello", thanks: "Thank you", excuse: "Excuse me", understand: "I don't understand",
  english: "Do you speak English?", doctor: "I need a doctor", police: "Call the police",
  water: "Still water, please", bill: "The bill, please",
};
const CAT = { bathroom: "essentials", howmuch: "essentials", help: "essentials", hello: "essentials", thanks: "essentials", excuse: "essentials", understand: "essentials", english: "essentials", doctor: "medical", police: "essentials", water: "dining", bill: "dining" };
const ALLERGEN_KEYS = ["peanuts","treeNuts","shellfish","fish","eggs","dairy","gluten","soy","penicillin","latex","beeStings","sesame"];

function mk(rows, allergyTemplate, medicationTemplate, allergens) {
  const phrases = rows.map(([id, local, phonetic]) => ({ id, english: EN[id], local, phonetic, category: CAT[id] }));
  return { phrases, allergyTemplate, medicationTemplate, allergens };
}

module.exports = {
  IDS, EN, CAT, ALLERGEN_KEYS,
  en: mk(IDS.map(id => [id, EN[id], "—"]), "I am allergic to %@.", "I take these medications:", {
    peanuts:"peanuts", treeNuts:"tree nuts", shellfish:"shellfish", fish:"fish", eggs:"eggs", dairy:"dairy / milk", gluten:"gluten / wheat", soy:"soy", penicillin:"penicillin", latex:"latex", beeStings:"bee stings", sesame:"sesame" }),
  pt: mk([["bathroom","Onde é a casa de banho?","OHN-deh eh ah KAH-zah deh BAHN-yoh"],["howmuch","Quanto custa?","KWAHN-too KOOSH-tah"],["help","Socorro!","soo-KOH-hoo"],["hello","Olá","oh-LAH"],["thanks","Obrigado","oh-bree-GAH-doo"],["excuse","Com licença","kohn lee-SEHN-sah"],["understand","Não entendo","nowN ehn-TEHN-doo"],["english","Fala inglês?","FAH-lah een-GLEHSH"],["doctor","Preciso de um médico","preh-SEE-zoo deh oon MEH-dee-koo"],["police","Chame a polícia","SHAH-meh ah poo-LEE-syah"],["water","Água sem gás, por favor","AH-gwah sayn gash poor fah-VOHR"],["bill","A conta, por favor","ah KOHN-tah poor fah-VOHR"]],
    "Sou alérgico a %@.", "Tomo estes medicamentos:", { peanuts:"amendoim", treeNuts:"frutos secos", shellfish:"marisco", fish:"peixe", eggs:"ovos", dairy:"leite e lacticínios", gluten:"glúten / trigo", soy:"soja", penicillin:"penicilina", latex:"látex", beeStings:"picadas de abelha", sesame:"sésamo" }),
  es: mk([["bathroom","¿Dónde está el baño?","DOHN-deh ehs-TAH el BAH-nyoh"],["howmuch","¿Cuánto cuesta?","KWAHN-toh KWEHS-tah"],["help","¡Socorro!","soh-KOH-roh"],["hello","Hola","OH-lah"],["thanks","Gracias","GRAH-syahs"],["excuse","Perdone","pehr-DOH-neh"],["understand","No entiendo","noh ehn-TYEHN-doh"],["english","¿Habla inglés?","AH-blah een-GLEHS"],["doctor","Necesito un médico","neh-seh-SEE-toh oon MEH-dee-koh"],["police","Llame a la policía","YAH-meh ah lah poh-lee-SEE-ah"],["water","Agua sin gas, por favor","AH-gwah seen gahs pohr fah-VOHR"],["bill","La cuenta, por favor","lah KWEHN-tah pohr fah-VOHR"]],
    "Soy alérgico a %@.", "Tomo estos medicamentos:", { peanuts:"cacahuetes", treeNuts:"frutos secos", shellfish:"mariscos", fish:"pescado", eggs:"huevos", dairy:"lácteos", gluten:"gluten / trigo", soy:"soja", penicillin:"penicilina", latex:"látex", beeStings:"picaduras de abeja", sesame:"sésamo" }),
  fr: mk([["bathroom","Où sont les toilettes ?","oo sohn lay twah-LET"],["howmuch","Combien ça coûte ?","kohm-BYEN sah koot"],["help","Au secours !","oh suh-KOOR"],["hello","Bonjour","bohn-ZHOOR"],["thanks","Merci","mehr-SEE"],["excuse","Excusez-moi","ex-kew-zay-MWAH"],["understand","Je ne comprends pas","zhuh nuh kohm-PRAHN pah"],["english","Parlez-vous anglais ?","par-lay-voo ahn-GLEH"],["doctor","J'ai besoin d'un médecin","zhay buh-ZWAN dun mayd-SAN"],["police","Appelez la police","ah-play lah poh-LEES"],["water","De l'eau plate, s'il vous plaît","duh loh plaht seel voo PLEH"],["bill","L'addition, s'il vous plaît","lah-dee-SYOHN seel voo PLEH"]],
    "Je suis allergique à %@.", "Je prends ces médicaments :", { peanuts:"arachides", treeNuts:"fruits à coque", shellfish:"fruits de mer", fish:"poisson", eggs:"œufs", dairy:"produits laitiers", gluten:"gluten / blé", soy:"soja", penicillin:"pénicilline", latex:"latex", beeStings:"piqûres d'abeille", sesame:"sésame" }),
  de: mk([["bathroom","Wo ist die Toilette?","voh ist dee toy-LET-teh"],["howmuch","Wie viel kostet das?","vee feel KOS-tet dahs"],["help","Hilfe!","HIL-feh"],["hello","Hallo","HAH-loh"],["thanks","Danke","DAHN-keh"],["excuse","Entschuldigung","ent-SHOOL-dee-goong"],["understand","Ich verstehe nicht","ikh fer-SHTAY-eh nikht"],["english","Sprechen Sie Englisch?","SHPREH-khen zee ENG-lish"],["doctor","Ich brauche einen Arzt","ikh BROW-kheh EYE-nen artst"],["police","Rufen Sie die Polizei","ROO-fen zee dee po-lee-TSY"],["water","Stilles Wasser, bitte","SHTIL-les VAH-ser BIT-teh"],["bill","Die Rechnung, bitte","dee REKH-noong BIT-teh"]],
    "Ich bin allergisch gegen %@.", "Ich nehme diese Medikamente:", { peanuts:"Erdnüsse", treeNuts:"Nüsse", shellfish:"Meeresfrüchte", fish:"Fisch", eggs:"Eier", dairy:"Milchprodukte", gluten:"Gluten / Weizen", soy:"Soja", penicillin:"Penicillin", latex:"Latex", beeStings:"Bienenstiche", sesame:"Sesam" }),
  it: mk([["bathroom","Dov'è il bagno?","doh-VEH eel BAHN-yoh"],["howmuch","Quanto costa?","KWAHN-toh KOHS-tah"],["help","Aiuto!","ah-YOO-toh"],["hello","Buongiorno","bwohn-JOR-noh"],["thanks","Grazie","GRAH-tsyeh"],["excuse","Mi scusi","mee SKOO-zee"],["understand","Non capisco","nohn kah-PEES-koh"],["english","Parla inglese?","PAR-lah een-GLEH-zeh"],["doctor","Ho bisogno di un medico","oh bee-ZOHN-yoh dee oon MEH-dee-koh"],["police","Chiami la polizia","KYAH-mee lah poh-lee-TSEE-ah"],["water","Acqua naturale, per favore","AH-kwah nah-too-RAH-leh pehr fah-VOH-reh"],["bill","Il conto, per favore","eel KOHN-toh pehr fah-VOH-reh"]],
    "Sono allergico a %@.", "Prendo questi farmaci:", { peanuts:"arachidi", treeNuts:"frutta a guscio", shellfish:"frutti di mare", fish:"pesce", eggs:"uova", dairy:"latticini", gluten:"glutine / grano", soy:"soia", penicillin:"penicillina", latex:"lattice", beeStings:"punture di ape", sesame:"sesamo" }),
  nl: mk([["bathroom","Waar is het toilet?","vahr is het twa-LET"],["howmuch","Hoeveel kost het?","HOO-fayl kost het"],["help","Help!","help"],["hello","Hallo","HAH-loh"],["thanks","Dank u wel","dahnk ew vel"],["excuse","Pardon","par-DON"],["understand","Ik begrijp het niet","ik buh-KHREYP het neet"],["english","Spreekt u Engels?","spraykt ew ENG-els"],["doctor","Ik heb een dokter nodig","ik hep un DOK-ter NOH-dikh"],["police","Bel de politie","bel duh poh-LEET-see"],["water","Plat water, alstublieft","plaht VAH-ter AHL-stew-bleeft"],["bill","De rekening, alstublieft","duh RAY-kuh-ning AHL-stew-bleeft"]],
    "Ik ben allergisch voor %@.", "Ik gebruik deze medicijnen:", { peanuts:"pinda's", treeNuts:"noten", shellfish:"schaaldieren", fish:"vis", eggs:"eieren", dairy:"zuivel", gluten:"gluten / tarwe", soy:"soja", penicillin:"penicilline", latex:"latex", beeStings:"bijensteken", sesame:"sesam" }),
  el: mk([["bathroom","Πού είναι η τουαλέτα;","poo EE-neh ee too-ah-LEH-tah"],["howmuch","Πόσο κοστίζει;","POH-soh kohs-TEE-zee"],["help","Βοήθεια!","voh-EE-thya"],["hello","Γεια σας","YAH sahs"],["thanks","Ευχαριστώ","ef-khah-rees-TOH"],["excuse","Συγγνώμη","seegh-NOH-mee"],["understand","Δεν καταλαβαίνω","dhen kah-tah-lah-VEH-noh"],["english","Μιλάτε αγγλικά;","mee-LAH-teh ahng-glee-KAH"],["doctor","Χρειάζομαι γιατρό","khree-AH-zoh-meh yah-TROH"],["police","Καλέστε την αστυνομία","kah-LEHS-teh teen ahs-tee-noh-MEE-ah"],["water","Ένα νερό, παρακαλώ","EH-nah neh-ROH pah-rah-kah-LOH"],["bill","Τον λογαριασμό, παρακαλώ","tohn loh-ghah-ryahs-MOH pah-rah-kah-LOH"]],
    "Είμαι αλλεργικός στο %@.", "Παίρνω αυτά τα φάρμακα:", { peanuts:"φιστίκια", treeNuts:"ξηροί καρποί", shellfish:"θαλασσινά", fish:"ψάρι", eggs:"αυγά", dairy:"γαλακτοκομικά", gluten:"γλουτένη / σιτάρι", soy:"σόγια", penicillin:"πενικιλίνη", latex:"λάτεξ", beeStings:"τσιμπήματα μέλισσας", sesame:"σουσάμι" }),
  tr: mk([["bathroom","Tuvalet nerede?","too-vah-LET NEH-reh-deh"],["howmuch","Ne kadar?","neh kah-DAR"],["help","İmdat!","eem-DAHT"],["hello","Merhaba","MEHR-hah-bah"],["thanks","Teşekkür ederim","teh-shek-KEWR eh-deh-reem"],["excuse","Affedersiniz","ahf-feh-DEHR-see-neez"],["understand","Anlamıyorum","ahn-LAH-muh-yoh-room"],["english","İngilizce biliyor musunuz?","een-gee-LEEZ-jeh bee-lee-YOHR moo-soo-nooz"],["doctor","Doktora ihtiyacım var","dohk-toh-RAH eeh-tee-yah-JUHM vahr"],["police","Polisi arayın","poh-lee-SEE ah-rah-YUHN"],["water","Su, lütfen","soo LEWT-fehn"],["bill","Hesap, lütfen","heh-SAHP LEWT-fehn"]],
    "%@ alerjim var.", "Bu ilaçları kullanıyorum:", { peanuts:"yer fıstığına", treeNuts:"kuruyemişlere", shellfish:"kabuklu deniz ürünlerine", fish:"balığa", eggs:"yumurtaya", dairy:"süt ürünlerine", gluten:"glütene / buğdaya", soy:"soyaya", penicillin:"penisiline", latex:"latekse", beeStings:"arı sokmasına", sesame:"susama" }),
  pl: mk([["bathroom","Gdzie jest toaleta?","g-jeh yest toh-ah-LEH-tah"],["howmuch","Ile to kosztuje?","EE-leh toh kohsh-TOO-yeh"],["help","Pomocy!","poh-MOH-tsih"],["hello","Dzień dobry","jen DOH-brih"],["thanks","Dziękuję","jen-KOO-yeh"],["excuse","Przepraszam","psheh-PRAH-shahm"],["understand","Nie rozumiem","nyeh roh-ZOO-myem"],["english","Czy mówi pan po angielsku?","chih MOO-vee pahn poh ahn-GYEL-skoo"],["doctor","Potrzebuję lekarza","poh-tsheh-BOO-yeh leh-KAH-zhah"],["police","Proszę wezwać policję","PROH-sheh VEZ-vahch poh-LEE-tsyeh"],["water","Woda niegazowana, poproszę","VOH-dah nyeh-gah-zoh-VAH-nah poh-PROH-sheh"],["bill","Rachunek, poproszę","rah-KHOO-nek poh-PROH-sheh"]],
    "Mam alergię na %@.", "Przyjmuję te leki:", { peanuts:"orzeszki ziemne", treeNuts:"orzechy", shellfish:"owoce morza", fish:"ryby", eggs:"jajka", dairy:"nabiał", gluten:"gluten / pszenicę", soy:"soję", penicillin:"penicylinę", latex:"lateks", beeStings:"użądlenia pszczół", sesame:"sezam" }),
  cs: mk([["bathroom","Kde je toaleta?","g-deh yeh toh-ah-LEH-tah"],["howmuch","Kolik to stojí?","KOH-lik toh STOH-yee"],["help","Pomoc!","POH-mots"],["hello","Dobrý den","DOH-bree den"],["thanks","Děkuji","DYEH-koo-yi"],["excuse","Promiňte","PROH-min-teh"],["understand","Nerozumím","NEH-roh-zoo-meem"],["english","Mluvíte anglicky?","MLOO-vee-teh AHN-glits-kih"],["doctor","Potřebuji lékaře","POH-tsheh-boo-yi LEH-kah-zheh"],["police","Zavolejte policii","ZAH-voh-ley-teh poh-LEE-tsee-yi"],["water","Neperlivou vodu, prosím","NEH-per-li-voh VOH-doo PROH-seem"],["bill","Účet, prosím","OO-chet PROH-seem"]],
    "Jsem alergický na %@.", "Beru tyto léky:", { peanuts:"arašídy", treeNuts:"ořechy", shellfish:"mořské plody", fish:"ryby", eggs:"vejce", dairy:"mléčné výrobky", gluten:"lepek / pšenici", soy:"sóju", penicillin:"penicilin", latex:"latex", beeStings:"včelí bodnutí", sesame:"sezam" }),
  hu: mk([["bathroom","Hol van a mosdó?","hohl vahn ah MOHSH-doh"],["howmuch","Mennyibe kerül?","MEN-nyi-beh KEH-rewl"],["help","Segítség!","SHEH-geet-shayg"],["hello","Jó napot","yoh NAH-poht"],["thanks","Köszönöm","KUH-suh-nuhm"],["excuse","Elnézést","EL-nay-zaysht"],["understand","Nem értem","nem AYR-tem"],["english","Beszél angolul?","BEH-sayl AHN-goh-lool"],["doctor","Orvosra van szükségem","OHR-vosh-rah vahn SEWK-shay-gem"],["police","Hívja a rendőrséget","HEEV-yah ah REND-uhr-shay-get"],["water","Szénsavmentes vizet kérek","SAYN-shahv-men-tesh VEE-zet KAY-rek"],["bill","A számlát, legyen szíves","ah SAHM-laht LEH-dyen SEE-vesh"]],
    "Allergiás vagyok a %@-ra.", "Ezeket a gyógyszereket szedem:", { peanuts:"földimogyoró", treeNuts:"diófélék", shellfish:"tenger gyümölcsei", fish:"hal", eggs:"tojás", dairy:"tejtermékek", gluten:"glutén / búza", soy:"szója", penicillin:"penicillin", latex:"latex", beeStings:"méhcsípés", sesame:"szezám" }),
  ro: mk([["bathroom","Unde este toaleta?","OON-deh YES-teh toh-ah-LEH-tah"],["howmuch","Cât costă?","kuht KOHS-tuh"],["help","Ajutor!","ah-zhoo-TOHR"],["hello","Bună ziua","BOO-nuh ZEE-wah"],["thanks","Mulțumesc","mool-tsoo-MESK"],["excuse","Scuzați-mă","skoo-ZAH-tsee muh"],["understand","Nu înțeleg","noo uhn-tseh-LEG"],["english","Vorbiți engleză?","vor-BEETS ehn-GLEH-zuh"],["doctor","Am nevoie de un doctor","ahm neh-VOY-eh deh oon DOHK-tohr"],["police","Chemați poliția","keh-MAHTS poh-LEE-tsee-ah"],["water","Apă plată, vă rog","AH-puh PLAH-tuh vuh rohg"],["bill","Nota, vă rog","NOH-tah vuh rohg"]],
    "Sunt alergic la %@.", "Iau aceste medicamente:", { peanuts:"arahide", treeNuts:"nuci", shellfish:"fructe de mare", fish:"pește", eggs:"ouă", dairy:"lactate", gluten:"gluten / grâu", soy:"soia", penicillin:"penicilină", latex:"latex", beeStings:"înțepături de albină", sesame:"susan" }),
  ru: mk([["bathroom","Где туалет?","gdyeh too-ah-LYET"],["howmuch","Сколько это стоит?","SKOHL-kah EH-tah STOH-eet"],["help","Помогите!","pah-mah-GHEE-tyeh"],["hello","Здравствуйте","ZDRAH-stvooy-tyeh"],["thanks","Спасибо","spah-SEE-bah"],["excuse","Извините","eez-vee-NEE-tyeh"],["understand","Я не понимаю","yah nyeh pah-nee-MAH-yoo"],["english","Вы говорите по-английски?","vih gah-vah-REE-tyeh pah-ahn-GLEE-skee"],["doctor","Мне нужен врач","mnyeh NOO-zhen vrahch"],["police","Вызовите полицию","VIH-zah-vee-tyeh pah-LEE-tsee-yoo"],["water","Воду без газа, пожалуйста","VOH-doo byez GAH-zah pah-ZHAH-loo-stah"],["bill","Счёт, пожалуйста","shchyoht pah-ZHAH-loo-stah"]],
    "У меня аллергия на %@.", "Я принимаю эти лекарства:", { peanuts:"арахис", treeNuts:"орехи", shellfish:"морепродукты", fish:"рыбу", eggs:"яйца", dairy:"молочные продукты", gluten:"глютен / пшеницу", soy:"сою", penicillin:"пенициллин", latex:"латекс", beeStings:"укусы пчёл", sesame:"кунжут" }),
  uk: mk([["bathroom","Де туалет?","deh too-ah-LET"],["howmuch","Скільки це коштує?","SKIL-kih tseh kohsh-TOO-yeh"],["help","Допоможіть!","doh-poh-moh-ZHEET"],["hello","Добрий день","DOH-brihy den"],["thanks","Дякую","DYAH-koo-yoo"],["excuse","Вибачте","VIH-bahch-teh"],["understand","Я не розумію","yah neh roh-zoo-MEE-yoo"],["english","Ви розмовляєте англійською?","vih rohz-mohv-LYAH-yeh-teh ahn-GLIY-skoh-yoo"],["doctor","Мені потрібен лікар","meh-NEE poh-TREE-ben LEE-kar"],["police","Викличте поліцію","VIH-klich-teh poh-LEE-tsee-yoo"],["water","Воду без газу, будь ласка","VOH-doo bez GAH-zoo bood LAHS-kah"],["bill","Рахунок, будь ласка","rah-KHOO-nohk bood LAHS-kah"]],
    "У мене алергія на %@.", "Я приймаю ці ліки:", { peanuts:"арахіс", treeNuts:"горіхи", shellfish:"морепродукти", fish:"рибу", eggs:"яйця", dairy:"молочні продукти", gluten:"глютен / пшеницю", soy:"сою", penicillin:"пеніцилін", latex:"латекс", beeStings:"укуси бджіл", sesame:"кунжут" }),
  sv: mk([["bathroom","Var är toaletten?","vahr air twa-LET-en"],["howmuch","Vad kostar det?","vahd KOS-tar deh"],["help","Hjälp!","yelp"],["hello","Hej","hey"],["thanks","Tack","tahk"],["excuse","Ursäkta","OOR-shek-tah"],["understand","Jag förstår inte","yahg fur-STOHR IN-teh"],["english","Talar du engelska?","TAH-lar doo ENG-el-skah"],["doctor","Jag behöver en läkare","yahg beh-HUH-ver en LEH-kah-reh"],["police","Ring polisen","ring poo-LEE-sen"],["water","Stilla vatten, tack","STIL-lah VAT-ten tahk"],["bill","Notan, tack","NOO-tahn tahk"]],
    "Jag är allergisk mot %@.", "Jag tar dessa mediciner:", { peanuts:"jordnötter", treeNuts:"nötter", shellfish:"skaldjur", fish:"fisk", eggs:"ägg", dairy:"mejeriprodukter", gluten:"gluten / vete", soy:"soja", penicillin:"penicillin", latex:"latex", beeStings:"bistick", sesame:"sesam" }),
  no: mk([["bathroom","Hvor er toalettet?","voor air too-ah-LET-eh"],["howmuch","Hvor mye koster det?","voor MEE-eh KOS-ter deh"],["help","Hjelp!","yelp"],["hello","Hei","hay"],["thanks","Takk","tahk"],["excuse","Unnskyld","OON-shil"],["understand","Jeg forstår ikke","yai for-STOHR IK-keh"],["english","Snakker du engelsk?","SNAHK-ker doo ENG-elsk"],["doctor","Jeg trenger en lege","yai TREHNG-er en LEH-geh"],["police","Ring politiet","ring poo-lee-TEE-eh"],["water","Vann uten kullsyre, takk","vahn OO-ten KOOL-see-reh tahk"],["bill","Regningen, takk","RYE-ning-en tahk"]],
    "Jeg er allergisk mot %@.", "Jeg tar disse medisinene:", { peanuts:"peanøtter", treeNuts:"nøtter", shellfish:"skalldyr", fish:"fisk", eggs:"egg", dairy:"melkeprodukter", gluten:"gluten / hvete", soy:"soya", penicillin:"penicillin", latex:"lateks", beeStings:"biestikk", sesame:"sesam" }),
  da: mk([["bathroom","Hvor er toilettet?","vor air toy-LET-eth"],["howmuch","Hvad koster det?","vath KOS-ter deh"],["help","Hjælp!","yelp"],["hello","Hej","hi"],["thanks","Tak","tahk"],["excuse","Undskyld","OON-skil"],["understand","Jeg forstår ikke","yai for-STOR IK-keh"],["english","Taler du engelsk?","TAH-ler doo ENG-elsk"],["doctor","Jeg har brug for en læge","yai har broo for en LEH-eh"],["police","Ring til politiet","ring til poh-lee-TEE-eth"],["water","Vand uden brus, tak","vahn OO-then broos tahk"],["bill","Regningen, tak","RYE-ning-en tahk"]],
    "Jeg er allergisk over for %@.", "Jeg tager denne medicin:", { peanuts:"jordnødder", treeNuts:"nødder", shellfish:"skaldyr", fish:"fisk", eggs:"æg", dairy:"mejeriprodukter", gluten:"gluten / hvede", soy:"soja", penicillin:"penicillin", latex:"latex", beeStings:"bistik", sesame:"sesam" }),
  fi: mk([["bathroom","Missä on vessa?","MIS-sa on VES-sah"],["howmuch","Paljonko se maksaa?","PAHL-yon-koh seh MAHK-sah"],["help","Apua!","AH-poo-ah"],["hello","Hei","hay"],["thanks","Kiitos","KEE-tohs"],["excuse","Anteeksi","AHN-tehk-see"],["understand","En ymmärrä","en EWM-mar-ra"],["english","Puhutko englantia?","POO-hoot-koh ENG-lahn-tee-ah"],["doctor","Tarvitsen lääkärin","TAR-veet-sen LAA-ka-rin"],["police","Soittakaa poliisi","SOYT-tah-kah poh-LEE-see"],["water","Vettä ilman hiilihappoa, kiitos","VET-ta EEL-mahn HEE-lee-hahp-poh-ah KEE-tohs"],["bill","Lasku, kiitos","LAHS-koo KEE-tohs"]],
    "Olen allerginen %@:lle.", "Käytän näitä lääkkeitä:", { peanuts:"maapähkinöille", treeNuts:"pähkinöille", shellfish:"äyriäisille", fish:"kalalle", eggs:"kananmunille", dairy:"maitotuotteille", gluten:"gluteenille / vehnälle", soy:"soijalle", penicillin:"penisilliinille", latex:"lateksille", beeStings:"mehiläisen pistoille", sesame:"seesamille" }),
  hr: mk([["bathroom","Gdje je WC?","g-dyeh yeh veh-TSEH"],["howmuch","Koliko košta?","KOH-lee-koh KOHSH-tah"],["help","Upomoć!","OO-poh-mohch"],["hello","Dobar dan","DOH-bar dahn"],["thanks","Hvala","HVAH-lah"],["excuse","Oprostite","oh-PROHS-tee-teh"],["understand","Ne razumijem","neh rah-ZOO-mee-yem"],["english","Govorite li engleski?","goh-VOH-ree-teh lee ehn-GLEHS-kee"],["doctor","Trebam liječnika","TREH-bahm lee-YECH-nee-kah"],["police","Zovite policiju","ZOH-vee-teh poh-LEE-tsee-yoo"],["water","Negaziranu vodu, molim","neh-gah-ZEE-rah-noo VOH-doo MOH-leem"],["bill","Račun, molim","RAH-choon MOH-leem"]],
    "Alergičan sam na %@.", "Uzimam ove lijekove:", { peanuts:"kikiriki", treeNuts:"orašaste plodove", shellfish:"morske plodove", fish:"ribu", eggs:"jaja", dairy:"mliječne proizvode", gluten:"gluten / pšenicu", soy:"soju", penicillin:"penicilin", latex:"lateks", beeStings:"ubode pčela", sesame:"sezam" }),
  zh: mk([["bathroom","洗手间在哪里？","shee-show-jyen dzai NAH-lee"],["howmuch","多少钱？","dwoh-shaow chyen"],["help","救命！","jyow-ming"],["hello","你好","nee-haow"],["thanks","谢谢","shyeh-shyeh"],["excuse","不好意思","boo-haow-EE-si"],["understand","我不明白","woh boo ming-bai"],["english","你会说英语吗？","nee hway shwoh ying-yoo mah"],["doctor","我需要看医生","woh shyoo-yaow kahn ee-shung"],["police","请叫警察","ching jyaow jing-chah"],["water","请给我一杯水","ching gay woh ee-bay shway"],["bill","买单","my-dahn"]],
    "我对%@过敏。", "我正在服用这些药物：", { peanuts:"花生", treeNuts:"坚果", shellfish:"贝类海鲜", fish:"鱼", eggs:"鸡蛋", dairy:"乳制品", gluten:"麸质／小麦", soy:"大豆", penicillin:"青霉素", latex:"乳胶", beeStings:"蜂蜇", sesame:"芝麻" }),
  ko: mk([["bathroom","화장실이 어디예요?","hwa-jang-shil-ee uh-dee-YEH-yo"],["howmuch","얼마예요?","ul-ma-YEH-yo"],["help","도와주세요!","do-wa-ju-SEH-yo"],["hello","안녕하세요","an-nyung-ha-SEH-yo"],["thanks","감사합니다","gam-sa-ham-NEE-da"],["excuse","실례합니다","shil-lyeh-ham-NEE-da"],["understand","이해가 안 돼요","ee-heh-ga an DWAE-yo"],["english","영어 할 줄 아세요?","yung-uh hal jool ah-SEH-yo"],["doctor","의사가 필요해요","ui-sa-ga pil-yo-HAE-yo"],["police","경찰을 불러 주세요","gyung-chal-eul bul-luh ju-SEH-yo"],["water","물 주세요","mool ju-SEH-yo"],["bill","계산서 주세요","gye-san-suh ju-SEH-yo"]],
    "저는 %@ 알레르기가 있어요.", "저는 이 약을 복용하고 있어요:", { peanuts:"땅콩", treeNuts:"견과류", shellfish:"조개류", fish:"생선", eggs:"달걀", dairy:"유제품", gluten:"글루텐/밀", soy:"콩", penicillin:"페니실린", latex:"라텍스", beeStings:"벌침", sesame:"참깨" }),
  vi: mk([["bathroom","Nhà vệ sinh ở đâu?","nyah veh sing uh DOH"],["howmuch","Bao nhiêu tiền?","bow nyew tyen"],["help","Cứu tôi với!","kuh-oo toy vuh-ee"],["hello","Xin chào","sin chow"],["thanks","Cảm ơn","kahm uhn"],["excuse","Xin lỗi","sin loy"],["understand","Tôi không hiểu","toy khohng hyew"],["english","Bạn nói tiếng Anh không?","bahn noy tyeng ahn khohng"],["doctor","Tôi cần bác sĩ","toy kuhn bahk see"],["police","Gọi cảnh sát","goy kahn saht"],["water","Cho tôi nước suối","chaw toy nook swoy"],["bill","Tính tiền","ting tyen"]],
    "Tôi bị dị ứng với %@.", "Tôi đang dùng các loại thuốc này:", { peanuts:"đậu phộng", treeNuts:"các loại hạt", shellfish:"hải sản có vỏ", fish:"cá", eggs:"trứng", dairy:"sữa và chế phẩm từ sữa", gluten:"gluten / lúa mì", soy:"đậu nành", penicillin:"penicillin", latex:"cao su latex", beeStings:"ong đốt", sesame:"mè" }),
  id: mk([["bathroom","Di mana kamar kecil?","dee MAH-nah KAH-mar keh-CHEEL"],["howmuch","Berapa harganya?","beh-RAH-pah har-GAHN-yah"],["help","Tolong!","TOH-long"],["hello","Halo","HAH-loh"],["thanks","Terima kasih","teh-REE-mah KAH-see"],["excuse","Permisi","per-MEE-see"],["understand","Saya tidak mengerti","SAH-yah TEE-dak meng-ER-tee"],["english","Apakah Anda bisa bahasa Inggris?","AH-pah-kah AHN-dah BEE-sah bah-HAH-sah ING-grees"],["doctor","Saya perlu dokter","SAH-yah PER-loo DOHK-ter"],["police","Panggil polisi","PANG-gil poh-LEE-see"],["water","Air putih, tolong","AH-eer POO-tee TOH-long"],["bill","Minta bon","MIN-tah bon"]],
    "Saya alergi terhadap %@.", "Saya minum obat-obatan ini:", { peanuts:"kacang tanah", treeNuts:"kacang pohon", shellfish:"kerang-kerangan", fish:"ikan", eggs:"telur", dairy:"produk susu", gluten:"gluten / gandum", soy:"kedelai", penicillin:"penisilin", latex:"lateks", beeStings:"sengatan lebah", sesame:"wijen" }),
  hi: mk([["bathroom","बाथरूम कहाँ है?","BAHTH-room kah-HAAN hai"],["howmuch","कितने का है?","KIT-neh kah hai"],["help","बचाओ!","bah-CHAO"],["hello","नमस्ते","nah-mah-STEH"],["thanks","धन्यवाद","dhahn-yah-VAAD"],["excuse","माफ़ कीजिए","maaf KEE-jee-eh"],["understand","मुझे समझ नहीं आया","MOO-jheh SUM-ujh nah-heen AH-yah"],["english","क्या आप अंग्रेज़ी बोलते हैं?","kyah aap an-GREH-zee BOHL-teh hain"],["doctor","मुझे डॉक्टर चाहिए","MOO-jheh DOK-tar CHAH-hee-eh"],["police","पुलिस बुलाइए","poo-LEES boo-LAH-ee-eh"],["water","पानी दीजिए","PAH-nee DEE-jee-eh"],["bill","बिल दीजिए","bil DEE-jee-eh"]],
    "मुझे %@ से एलर्जी है।", "मैं ये दवाएँ लेता हूँ:", { peanuts:"मूंगफली", treeNuts:"मेवे", shellfish:"शेलफिश", fish:"मछली", eggs:"अंडे", dairy:"दूध से बनी चीज़ें", gluten:"ग्लूटेन / गेहूँ", soy:"सोया", penicillin:"पेनिसिलिन", latex:"लेटेक्स", beeStings:"मधुमक्खी के डंक", sesame:"तिल" }),
  he: mk([["bathroom","איפה השירותים?","EY-foh hah-sheh-roo-TEEM"],["howmuch","כמה זה עולה?","KAH-mah zeh oh-LEH"],["help","הצילו!","hah-TSEE-loo"],["hello","שלום","shah-LOHM"],["thanks","תודה","toh-DAH"],["excuse","סליחה","slee-KHAH"],["understand","אני לא מבין","ah-NEE loh meh-VEEN"],["english","אתה מדבר אנגלית?","ah-TAH meh-dah-BEHR ahn-GLEET"],["doctor","אני צריך רופא","ah-NEE tsah-REEKH roh-FEH"],["police","תתקשרו למשטרה","teet-kah-SHROO lah-meesh-tah-RAH"],["water","מים בבקשה","MAH-yeem beh-vah-kah-SHAH"],["bill","חשבון בבקשה","khesh-BOHN beh-vah-kah-SHAH"]],
    "אני אלרגי ל%@.", "אני נוטל את התרופות האלה:", { peanuts:"בוטנים", treeNuts:"אגוזים", shellfish:"פירות ים", fish:"דגים", eggs:"ביצים", dairy:"מוצרי חלב", gluten:"גלוטן / חיטה", soy:"סויה", penicillin:"פניצילין", latex:"לטקס", beeStings:"עקיצות דבורים", sesame:"שומשום" }),
  arm: mk([["bathroom","أين الحمام؟","AYN al-ham-MAAM"],["howmuch","بكم هذا؟","bee-KAM HAH-thah"],["help","النجدة!","an-NAJ-dah"],["hello","مرحبا","MAR-hah-bah"],["thanks","شكرا","SHOOK-ran"],["excuse","عفوا","AF-wan"],["understand","لا أفهم","lah AF-ham"],["english","هل تتكلم الإنجليزية؟","hal ta-ta-KAL-lam al-in-glee-ZEE-yah"],["doctor","أحتاج إلى طبيب","ah-TAAJ ee-lah tah-BEEB"],["police","اتصل بالشرطة","it-TAH-sil bish-SHOOR-tah"],["water","ماء من فضلك","MAA min FAD-lik"],["bill","الحساب من فضلك","al-hee-SAAB min FAD-lik"]],
    "لدي حساسية من %@.", "أتناول هذه الأدوية:", { peanuts:"الفول السوداني", treeNuts:"المكسرات", shellfish:"المحار", fish:"السمك", eggs:"البيض", dairy:"منتجات الألبان", gluten:"الغلوتين / القمح", soy:"الصويا", penicillin:"البنسلين", latex:"اللاتكس", beeStings:"لسعات النحل", sesame:"السمسم" }),
  sw: mk([["bathroom","Choo kiko wapi?","CHOH-oh KEE-koh WAH-pee"],["howmuch","Bei gani?","bay GAH-nee"],["help","Msaada!","m-sah-AH-dah"],["hello","Jambo","JAHM-boh"],["thanks","Asante","ah-SAHN-teh"],["excuse","Samahani","sah-mah-HAH-nee"],["understand","Sielewi","see-eh-LEH-wee"],["english","Unazungumza Kiingereza?","oo-nah-zoon-GOOM-zah kee-een-geh-REH-zah"],["doctor","Nahitaji daktari","nah-hee-TAH-jee dahk-TAH-ree"],["police","Ita polisi","EE-tah poh-LEE-see"],["water","Maji, tafadhali","MAH-jee tah-fah-DHAH-lee"],["bill","Bili, tafadhali","BEE-lee tah-fah-DHAH-lee"]],
    "Nina mzio wa %@.", "Ninatumia dawa hizi:", { peanuts:"karanga", treeNuts:"njugu", shellfish:"samakigamba", fish:"samaki", eggs:"mayai", dairy:"bidhaa za maziwa", gluten:"gluteni / ngano", soy:"soya", penicillin:"penisilini", latex:"mpira wa latex", beeStings:"kuumwa na nyuki", sesame:"ufuta" }),
};
